# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5acad64204f01fde086824ea1e168e2de662a091a35bbb047fd85048841b9cc27c358bd2381913a592b8765cd6512d1847ee299264e84519b17977ff338fb7ec

test:
  secret_key_base: 4c4aeaf0e177c66395b9dfb619d8ccfd24c2d55ca33098b5fdbacf5d492ea9a58c5657dc873f97599ab3277171a3d4647f52c58fb739d090f95f5a373e62c00b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
